### ISSUE TITLE
doesn't make any sense

### ISSUE THREAD

**Issue by Myev04** [DDDinggo22/Osu-Bot#1]
Can you make instructions to use it?
I already compiled it tried everything with osu! settings it doesn't move.
It just freezes the cursor in the place.

**Comment by TheCodingNina** [comment]
Currently the bot is outdated. I will push an update in a couple of hours. The problem you have encountered is that the timer pointer, what the bot uses to sync to the game, points to the wrong address.

If you want to update this pointer yourself. Search for the time with something like Cheat Engine, this can be done easily in edit mode on osu!, and make a pointer of that address. Then put the pointer as the TimerPointer for Osu!Bot. You can change this via the settings tab or manually in the configFile.

**Comment by TheCodingNina** [comment]
I have updated the bot. You can download a pre-compiled .exe from the releases page.
And for instructions how to install/use can be found at the main page of this repo or in the README.md.
Also if you need to update the timerPointer again, the latest working can now be found under the instructions.
