### ISSUE TITLE
Cursor does not move.

### ISSUE THREAD

**Issue by Boii1** [DDDinggo22/Osu-Bot#3]
Seems that the bot IS getting the cursor and it's movement, but it doesn't take any action when the song starts.

**Comment by TheCodingNina** [comment]
You need to update the timerAddress pointer, it is outdated.
You can use this for a correct one:

[Timer Pointer]
Offset0 : 1c
Offset1 : 4c4
Offset2 : d0
Offset3 : 16c
Offset4 : 150
ThreadOffset : -32c

You can change it in the settings tab, or the configFile.cfg using a .txt editor.
I also updated the readme.md on the master branch

**Comment by Boii1** [comment]
Thanks.
