### ISSUE TITLE
Inaccurate

### ISSUE THREAD

**Issue by JakeDahl** [DDDinggo22/Osu-Bot#5]
Just seems to be a bit off, sometimes it won't even go for a beat.

**Comment by JakeDahl** [comment]
Click times are also intermittent. Often clicks wrong time or just avoids hit object.

**Comment by JakeDahl** [comment]
https://youtu.be/qs9sg_Gy0Dg

**Comment by TheCodingNina** [comment]
With the Halloween update, I have fixed many bugs that could have caused the behavior that you have experienced. I recommend updating to the latest version and try if it still gives these problems.

**Comment by JakeDahl** [comment]
Yes it appears that was the issue. Thanks
